Enpadi_WebUI/Controllers/NavigationController.cs
using Enpadi_WebUI.Models;
using System.Collections.Generic;
using Microsoft.AspNet.Identity;
using System.Web.Mvc;
using System.Linq;
using System;
using System.Configuration;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Security.Claims;

namespace Enpadi_WebUI.Controllers
{
    public class NavigationController : Controller
    {
        //private ApplicationDbContext db = new ApplicationDbContext();
        private static Boolean Confirm_email = Boolean.Parse(ConfigurationManager.AppSettings[UserValidation.Confirm_email]);

        // GET: Header
        [ChildActionOnly]
        public ActionResult EnpadiHeader()
        {
            ApplicationDbContext db = new ApplicationDbContext();
            ViewModelNavigation perfil = new ViewModelNavigation();

            //Entradas
            string strSQL = "SELECT COALESCE(SUM(abono1),0) As Total FROM Transacciones WHERE socioID > 0 AND TarjetaID > 0 AND tipoID IN (1,2) AND fechaBaja IS NULL";
            IEnumerable<total> Entradas = db.Database.SqlQuery<total>(strSQL);
            perfil.entradas = Entradas.ToList().FirstOrDefault().Total;

            //Salidas
            strSQL = "SELECT COALESCE(SUM(cargo1 * -1),0) As Total FROM Transacciones WHERE socioID > 0 AND TarjetaID > 0 AND tipoID IN (1,2) AND fechaBaja IS NULL";
            IEnumerable<total> Salidas = db.Database.SqlQuery<total>(strSQL);
            perfil.salidas = Salidas.ToList().FirstOrDefault().Total;

            //Comisiones Cobradas
            strSQL = "SELECT COALESCE(SUM(abono2 + abono2iva + cargo3 + cargo3iva + cargo4 + cargo4iva + cargo6 + cargo6iva),0) As Total FROM Transacciones WHERE  TarjetaID > 0 AND tipoID IN (1,2) AND fechaBaja IS NULL";
            IEnumerable<total> Cobradas = db.Database.SqlQuery<total>(strSQL);
            perfil.comisionesCobradas = Cobradas.ToList().FirstOrDefault().Total;

            List<TransactionFee> trasnfee = db.TransactionFee.ToList();
            perfil.comisionesCobradas += trasnfee.Sum(x => x.FixAmount);
            perfil.comisionesCobradas += trasnfee.Sum(x => x.VariableAmount);
            perfil.comisionesCobradas += trasnfee.Sum(x => x.TaxFeeAmount);
            perfil.comisionesCobradas += trasnfee.Sum(x => x.ChargedByPartnerAmount);


            //Comisiones Pagadas
            //strSQL = "SELECT COALESCE(SUM((cargo2 + cargo2iva + cargo5 + cargo5iva) * -1),0) As Total FROM Transacciones WHERE socioID > 0 AND TarjetaID > 0 AND tipoID IN (1,2) AND fechaBaja IS NULL";
            //IEnumerable<total> Pagadas = db.Database.SqlQuery<total>(strSQL);
            //perfil.comisionesPagadas = Pagadas.ToList().FirstOrDefault().Total;

            //Comisiones Facturables
            //strSQL = "SELECT COALESCE(SUM(facturable1 + facturable1iva),0) As Total FROM Transacciones WHERE fechaBaja IS NULL AND tipoID IN (1,2) AND pagado1 = 0";
            //IEnumerable<total> Facturables = db.Database.SqlQuery<total>(strSQL);
            //perfil.comisionesFacturables = Facturables.ToList().FirstOrDefault().Total;

            // Saldo Disponible
            strSQL = "SELECT COALESCE(SUM(abono2 + abono2iva - cargo2 - cargo2iva + cargo3 + cargo3iva + cargo4 + cargo4iva - cargo5 - cargo5iva + cargo6 + cargo6iva + facturable1 + facturable1iva),0) As Total FROM Transacciones WHERE TarjetaID > 0 AND tipoID IN (1,2) AND fechaBaja IS NULL";
            IEnumerable<total> saldoDisponible = db.Database.SqlQuery<total>(strSQL);
            perfil.saldoDisponible = saldoDisponible.ToList().FirstOrDefault().Total;

            perfil.saldoDisponible -= trasnfee.Sum(x => x.ChargedByPartnerAmount);

            foreach (TransactionFee item in trasnfee) {
                if(item.Fee.UserToPayId != null){
                    perfil.saldoDisponible -= trasnfee.Sum(x => x.FixAmount);
                    perfil.saldoDisponible -= trasnfee.Sum(x => x.VariableAmount);
                    perfil.saldoDisponible -= trasnfee.Sum(x => x.TaxFeeAmount);
                }
            }


            if (User.IsInRole("Administrador"))
            {
                return PartialView("_HeaderAdministrador", perfil);
            }

            return new EmptyResult();
        }


        // GET: Navigation
        [ChildActionOnly]
        public ActionResult EnpadiNavigation(string skin)
        {
            ApplicationDbContext db = new ApplicationDbContext();
            ViewModelNavigation perfil = new ViewModelNavigation();
            skin = "clean";
            // Skin Aplicacion
            string strSQL = String.Format("SELECT * FROM Skins WHERE name = '{0}'", skin);
            IEnumerable<skin> skinAplicacion = db.Database.SqlQuery<skin>(strSQL);
            ViewBag.skinApp = skinAplicacion.ToList().FirstOrDefault();

            if (User.IsInRole("Administrador"))
            {

                // Saldo Tiempo Aire
                strSQL = "SELECT SUM(abono1 + abono1iva + abono2 + abono2iva - cargo1 - cargo1iva - cargo2 - cargo2iva) As Total FROM Transacciones WHERE FechaBaja IS NULL AND socioID = 5";
                IEnumerable<total> TiempoAire = db.Database.SqlQuery<total>(strSQL);
                perfil.saldoTiempoAire = TiempoAire.ToList().FirstOrDefault().Total;

                // Saldo Pago de Servicios
                strSQL = "SELECT SUM(abono1 + abono1iva + abono2 + abono2iva - cargo1 - cargo1iva - cargo2 - cargo2iva) As Total FROM Transacciones WHERE FechaBaja IS NULL AND socioID = 6";
                IEnumerable<total> PagoServicios = db.Database.SqlQuery<total>(strSQL);
                perfil.saldoPagoServicios = PagoServicios.ToList().FirstOrDefault().Total;


                //// Saldo Tiempo Aire
                //strSQL = "SELECT SUM(abono1 + abono1iva + abono2 + abono2iva - cargo1 - cargo1iva - cargo2 - cargo2iva) As Total FROM Transacciones WHERE FechaBaja IS NULL AND socioID = 5";
                //IEnumerable<total> TiempoAire = db.Database.SqlQuery<total>(strSQL);
                //perfil.saldoTiempoAire = TiempoAire.ToList().FirstOrDefault().Total;

                //// Saldo Pago de Servicios
                //strSQL = "SELECT SUM((abono1 + abono1iva + abono2 + abono2iva) - (cargo1 - cargo1iva - cargo2 - cargo2iva)) As Total FROM Transacciones WHERE FechaBaja IS NULL AND socioID = 6";
                //IEnumerable<total> PagoServicios = db.Database.SqlQuery<total>(strSQL);
                //perfil.saldoPagoServicios = PagoServicios.ToList().FirstOrDefault().Total;

                return PartialView("_MenuAdministrador", perfil);
            }

            //TODO: if user is not on any role make a log of the error

            //get the user role

            //todo: check here

            Tools.GetUserRole(User);

            if (User.IsInRole("Socio"))
                return PartialView("_MenuSocio");

            if (User.IsInRole("Usuario"))
            {
                string currentUserId = User.Identity.GetUserId();
                tarjetas usuario = db.tarjetas.FirstOrDefault(x => x.password == currentUserId);
                perfil.usuario = usuario;

                strSQL = " SELECT ISNULL(SUM(abonoTotal-cargoTotal),0) As Total "
                       + " FROM Transacciones "
                       + " WHERE fechaBaja IS NULL AND tarjetaID = " + usuario.tarjetaID;
                IEnumerable<total> saldoActual = db.Database.SqlQuery<total>(strSQL);
                perfil.saldoActual = saldoActual.ToList().FirstOrDefault().Total;

                strSQL = " SELECT ISNULL(SUM(abono-cargo),0) As Total "
                       + " FROM Recompensas "
                       + "WHERE fechaBaja IS NULL AND tarjetaID = " + usuario.tarjetaID;
                IEnumerable<total> saldoRecompensas = db.Database.SqlQuery<total>(strSQL);
                perfil.saldoRecompensas = saldoRecompensas.ToList().FirstOrDefault().Total;

                return PartialView("_MenuUsuario", perfil);
            }

            if (User.IsInRole("Recompensas"))
                return PartialView("_MenuRecompensas");

            if (User.IsInRole("Remesas"))
                return PartialView("_MenuRemesas");

            if (User.IsInRole("Concentradora"))
            {
                string currentUserId = User.Identity.GetUserId();
                tarjetas usuario = db.tarjetas.FirstOrDefault(x => x.password == currentUserId);
                perfil.usuario = usuario;

                strSQL = " SELECT ISNULL(SUM(abonoTotal-cargoTotal),0) As Total "
                       + " FROM Transacciones "
                       + " WHERE fechaBaja IS NULL AND tarjetaID = " + usuario.tarjetaID;
                IEnumerable<total> saldoActual = db.Database.SqlQuery<total>(strSQL);
                perfil.saldoActual = saldoActual.ToList().FirstOrDefault().Total;

                strSQL = " SELECT ISNULL(SUM(abono-cargo),0) As Total "
                       + " FROM Recompensas "
                       + "WHERE fechaBaja IS NULL AND tarjetaID = " + usuario.tarjetaID;
                IEnumerable<total> saldoRecompensas = db.Database.SqlQuery<total>(strSQL);
                perfil.saldoRecompensas = saldoRecompensas.ToList().FirstOrDefault().Total;

                return PartialView("_MenuConcentradora", perfil);
            }

            return new EmptyResult();

        }
    }
}

Enpadi_WebUI/Views/Shared/_Header.cshtml
<div class="color-line">
</div>
<div id="logo" class="light-version; text-center" style="background-color:@string.Format("#{0}", ViewBag.skinApp.colorTitle);">
    <span>@ViewBag.skinApp.title</span>
</div>
<nav role="navigation">
    <div class="header-link hide-menu"><i class="fa fa-bars"></i></div>
    <div class="small-logo">
        <span class="text-primary">ENPADI APP</span>
    </div>
    <form role="search" class="navbar-form-custom" method="post" action="#">
        <div class="form-group">
            @*<input type="text" placeholder="Buscar..." class="form-control" name="search">*@
            
        </div>
    </form>
    <div class="navbar-right">
        @*<a href="@Url.Action("Terminos", "PanelUsuarios")"><span class="nav-label" style="margin-right:40px; margin-top:25px;">Terminos y Condiciones del Servicio</span><span class="label label-success pull-right"></span> </a>*@
        <ul class="nav navbar-nav no-borders">
            @*<li class="dropdown">
                <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                    <i class="pe-7s-speaker"></i>
                </a>
                <ul class="dropdown-menu hdropdown notification animated flipInX">
                    <li><a><span class="label label-success">NEW</span> It is a long established.</a></li>
                    <li><a><span class="label label-warning">WAR</span> There are many variations.</a></li>
                    <li><a><span class="label label-danger">ERR</span> Contrary to popular belief.</a></li>
                    <li class="summary"><a href="#">See all notifications</a></li>
                </ul>
            </li>*@
            @*<li class="dropdown">
                <a class="dropdown-toggle label-menu-corner" href="#" data-toggle="dropdown">
                    <i class="pe-7s-mail"></i>
                    <span class="label label-success">4</span>
                </a>
                <ul class="dropdown-menu hdropdown animated flipInX">
                    <div class="title">You have 4 new messages</div>
                    <li><a>It is a long established.</a></li>
                    <li><a>There are many variations.</a></li>
                    <li><a>Lorem Ipsum is simply dummy.</a></li>
                    <li><a>Contrary to popular belief.</a></li>
                    <li class="summary"><a href="#">See All Messages</a></li>
                </ul>
            </li>*@

            @Html.Action("EnpadiHeader", "Navigation")

            <li class="dropdown">
                <a href="@Url.Action("LogOff", "Account")" title="Cerrar Sesión">
                    <i class="pe-7s-upload pe-rotate-90" style="margin-right:10px;"></i>
                </a>
            </li>
        </ul>
    </div>
</nav>

Enpadi_WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>ENPADI | @ViewBag.Title</title>

    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
    <link href="~/Vendor/fontawesome/css/font-awesome.css" rel='stylesheet' type='text/css' />

    <!-- Primary vendor style -->
    @Styles.Render("~/bundles/font-awesome/css")
    @Styles.Render("~/bundles/animate/css")
    @Styles.Render("~/bundles/bootstrap/css")
    @Styles.Render("~/bundles/peicon7stroke/css")

    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}
                                              
    <!-- Primary HOMER style -->
    @Styles.Render("~/bundles/homer/css")
</head>
<body class="@Html.PageClass()" style="background-color:@string.Format("#{0}", ViewBag.skinApp.colorNavBar);">

    <!-- Simple splash screen-->
    <div class="splash">
        <div class="color-line"></div>
        <div class="splash-title">
            @{
                if (ViewBag.skinApp.loginImage != null)
                {
                    <img src="~/Images/@ViewBag.skinApp.loginImage" width="250" style="padding-top:15px;" />
                }
            }
            <p>Dispersión, Pagos, Servicios y Programas de valor</p>
        </div>
    </div>

    <!--[if lt IE 7]>
    <p class="alert alert-danger">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    <!-- Header -->
    <div id="header">
        @Html.Partial("_Header")
    </div>

    <!-- Navigation -->
    <aside id="menu" style="background-color:@string.Format("#{0}", ViewBag.skinApp.colorNavBar);">
        @Html.Partial("_Navigation")
    </aside>

    <!-- Main view  -->
    <div id="wrapper">
        @RenderBody()
    </div>

    <!-- Section for main scripts render -->
    @Scripts.Render("~/bundles/jquery/js")
    @Scripts.Render("~/bundles/bootstrap/js")
    @Scripts.Render("~/bundles/homer/js")

    <!-- Handler for local scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>

Enpadi_WebUI/Views/Shared/_LayoutEnpadiAdmin.cshtml
@using System.Configuration;
@{
    string pageRegion = ConfigurationManager.AppSettings["Region"].ToLower();
}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>ENPADI | @ViewBag.Title</title>

    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>

    <!-- Add local styles, mostly for plugins css file -->
    @*@if (IsSectionDefined("Styles"))
        {@RenderSection("Styles", required: false)}*@
    <!-- Primary HOMER style -->
    @Styles.Render("~/Content/bootstrap")
    @Styles.Render("~/bundles/font-awesome-4.7/css")
    @Styles.Render("~/bundles/animate/css")
    @*@Styles.Render("~/bundles/bootstrap/css")*@
    @Styles.Render("~/Content/LayoutNewMenu")
    @Styles.Render("~/Content/datatables")
    @Styles.Render("~/Content/_layout_website")


    @RenderSection("Styles", required: false)

    <!-- Section for main scripts render -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquery/js")
    @Scripts.Render("~/bundles/datatable")
    @Scripts.Render("~/bundles/datatableButtons")
    @Scripts.Render("~/bundles/bootstrap/js")
    @Scripts.Render("~/bundles/jquery/currency")
    @Scripts.Render("~/bundles/jqueryval")

    <!-- Handler for local scripts -->

</head>
<body class="kiosko">

    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="navbar-wrapper">
                    <div class="container-fluid">
                        <nav class="navbar navbar-fixed-top navbar-menu">
                            <div class="container">
                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                                        <span class="sr-only">Toggle navigation</span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>
                                </div>
                                <div id="navbar" class="navbar-collapse collapse">
                                    <ul class="nav navbar-nav">
                                        <li class="menu-logo-li">
                                            <img src="~/Images/enpadi-logo.png" class="menu-logo" />
                                        </li>
                                    </ul>
                                    <ul class="nav navbar-nav pull-right">
                                        <li class="dropdown">
                                            <a href="#" data-toggle="dropdown" class="dropdown-toggle">Reportes <b class="caret"></b></a>
                                            <ul class="dropdown-menu">
                                                <li id="reports"><a href="~/EnpadiAdmin/Reports?m=reports">Generales</a></li>
                                                <li class="divider"></li>
                                                <li id="kioskoreports"><a href="~/EnpadiAdmin/KioskoReport?m=kioskoreports">Kioskos</a></li>
                                            </ul>
                                        </li>
                                        <li id="logoff"><a href="~/EnpadiAdmin/logoff">LogOut</a></li>
                                    </ul>
                                    <ul class="nav navbar-nav pull-right">
                                        <li id="system" class="dropdown">
                                            <a href="#" data-toggle="dropdown" class="dropdown-toggle">Servicios <b class="caret"></b></a>
                                            <ul class="dropdown-menu">
                                                <li id="fees"><a href="~/EnpadiAdmin/fees?m=fees">Comisiones</a></li>
                                                <li id="services"><a href="~/EnpadiAdmin/Services?m=services">Services</a></li>
                                            </ul>
                                        </li>
                                    </ul>
                                    <ul class="nav navbar-nav pull-right">
                                        <li id="system" class="dropdown">
                                            <a href="#" data-toggle="dropdown" class="dropdown-toggle">Sistema <b class="caret"></b></a>
                                            <ul class="dropdown-menu">
                                                <li><a href="~/EnpadiAdmin/UserSettings">Usuarios</a></li>
                                                <li id="addpartner"><a href="~/EnpadiAdmin/Partner?m=addpartner">Socios(dev)</a></li>
                                            </ul>
                                        </li>
                                    </ul>
                                    <ul class="nav navbar-nav pull-right">
                                        <li id="index"><a href="~/EnpadiAdmin/index?m=index">Inicio</a></li>
                                        
                                    </ul>
                                   
                                </div>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        <div class="row main-content">
            <div class="col-lg-3">
                @*name*@
                <div class="row">
                    <div class="col-lg-12">
                        <div class="user-name">
                            <label id="lb_client_name">Administrador Enpadi</label>
                            @*@Model.user.Name.ToUpper()*@
                        </div>
                    </div>
                </div>
                @*first table*@
                <div class="row">
                    <div class="col-lg-12">

                        <div class="table-name">Res&uacute;men</div>
                        <div class="table-div data">
                            <div class="row">
                                <div class="col-lg-12 text-center">
                                    <i class="fa fa-bar-chart fa-align-center fa-5x" aria-hidden="true"></i>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12 text-center">
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <div class="enapdi-color">
                                                <label id="lb_diestel_celphone"></label>
                                                @*@Model.enpadiCard.creditoDisponible.ToString("C")*@
                                            </div>

                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <div class="enapdi-color">
                                                Diestel tiempo Aire
                                            </div>
                                            <hr class="table-division" />
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-lg-12 text-center">
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <div class="enapdi-color">
                                                <label id="lb_diestel_service"></label>
                                                @*@Model.enpadiCard.creditoDisponible.ToString("C")*@
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <div class="enapdi-color">
                                                Diestel servicios
                                            </div>
                                            <hr class="table-division" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                @*link to profile*@
                @*<div class="row">
                        <div class="col-lg-12">
                            <a href="~/website/profile">Actualiza los datos de la cuenta <b><u>AQUI</u></b></a>
                        </div>
                    </div>*@
            </div>
            <div class="col-lg-9">
                <!-- Main view  -->
                @RenderBody()
            </div>
        </div>

    </div>

</body>
</html>

<script type="text/javascript">
    function changeActive(el) {
        $(".li-menun-content").removeClass("active");

        $(el).addClass("active");
    }


    $(window).load(function () {
        $.ajax({
            url: '@Url.Action("LoadUser", "EnpadiAdmin")',
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (result) {
                console.log(result);
                $("#lb_diestel_celphone").text(result.DiestelPhoneTime).formatCurrency();
                $("#lb_diestel_service").text(result.DiestelServiceTime).formatCurrency();
                //$("#lb_enpadicard_nip").text(result.enpadiCard.tcNIP);
                //$("#lb_email").text(result.user.Email);
                //$("#lb_client_name").text(result.user.Name);

            },
            error: function (result) {
                console.log(result);
            }
        });


        //set the active li on the proper option
        $.urlParam = function (name) {
            var results = new RegExp('[\?&]' + name + '=([^&#]*)').exec(window.location.href);
            if (results == null) {
                return null;
            }
            return results[1] || 0;
        }
        var menuOption = $.urlParam('m');
        if (menuOption == null) {
            menuOption = "";
        }
        $('#' + menuOption).addClass('active');
    });
</script>

@RenderSection("Scripts", required: true)

Enpadi_WebUI/Views/Shared/_Layout_Blank.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>ENPADI | @ViewBag.Title</title>

    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>

    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

    <!-- Primary HOMER style -->
    @Styles.Render("~/bundles/font-awesome/css")
    @Styles.Render("~/bundles/animate/css")
    @Styles.Render("~/bundles/bootstrap/css")
    @Styles.Render("~/bundles/peicon7stroke/css")
    @Styles.Render("~/bundles/homer/css")

    <!-- Section for main scripts render -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquery/js")
    @Scripts.Render("~/bundles/bootstrap/js")
    @Scripts.Render("~/bundles/jquery/currency")
    @Scripts.Render("~/bundles/jqueryval")
</head>
<body class="blank">

    <!-- Simple splash screen-->
    <div class="splash">
        <div class="color-line"></div>
        <div class="splash-title">
            @{
                if (ViewBag.skinApp.loginImage != null)
                {
                    <img src="~/Images/@ViewBag.skinApp.loginImage" width="250" style="padding-top:15px;" />
                }
            }
            <p>Dispersión, Pagos, Servicios y Programas de valor</p>
        </div>
    </div>
    <!--[if lt IE 7]>
    <p class="alert alert-danger">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <div class="color-line"></div>

    @*<div class="pull-left m">
    <a href="@Url.Action("Index", "Dashboard")" class="btn btn-primary">Back to Dashboard</a>
    </div>*@

    <!-- Main view  -->
    @RenderBody()

    <!-- Section for main scripts render -->
    @Scripts.Render("~/bundles/jquery/js")
    @Scripts.Render("~/bundles/bootstrap/js")
    @Scripts.Render("~/bundles/homer/js")

    <!-- Handler for local scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>

Enpadi_WebUI/Views/Shared/_Layout_Error.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_Layout_Error</title>

    <!-- Primary HOMER style -->
    @Styles.Render("~/Content/bootstrap")
    @Styles.Render("~/bundles/font-awesome-4.7/css")
    @Styles.Render("~/bundles/animate/css")
    @*@Styles.Render("~/bundles/bootstrap/css")*@
    @Styles.Render("~/Content/LayoutNewMenu")
    @Styles.Render("~/Content/datatables")
    @Styles.Render("~/Content/_layout_website")


    @RenderSection("Styles", required: false)

    <!-- Section for main scripts render -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquery/js")
    @Scripts.Render("~/bundles/bootstrap/js")
    @Scripts.Render("~/bundles/jquery/currency")
    @Scripts.Render("~/bundles/jqueryval")

    <!-- Handler for local scripts -->
    @RenderSection("Scripts", required: false)
</head>
<body>

    <div class="navbar-wrapper">
        <div class="container-fluid">
            <nav class="navbar navbar-fixed-top navbar-menu">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div id="navbar" class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li class="menu-logo-li">
                                <img src="~/Images/enpadi-logo.png" class="menu-logo" />
                            </li>
                        </ul>
                        <ul class="nav navbar-nav pull-right">
                            <li id="index"><a href="~/website/index?m=index">Inicio</a></li>
                            <li id="company"><a href="~/website/company?m=company">Empresas</a></li>
                            <li id="clients"><a href="~/website/clients?m=clients">Individuos</a></li>
                            <li id="contact"><a href="~/website/contact?m=contact">Contacto</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    </div>



    <div class="container">

        <!-- Main view  -->
        @RenderBody()

        <div class="row">


            <div class="col-lg-12">
                <div class="footer-content" style="background-color:#003366">
                    <h1 class="footer-title">enpadi</h1>
                    <hr style="width: 250px;" />
                    @@ Derechos reservados 2017 ENPADI.
                    <br />
                </div>
            </div>
        </div>
    </div>
</body>
</html>

Enpadi_WebUI/Views/Shared/_Navigation.cshtml
<!-- Despliega el Menu en base a los Roles del Usuario -->
@Html.Action("EnpadiNavigation", "Navigation")