Enpadi_WebUI/Models/Service.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Enpadi_WebUI.Models
{
    [Table("Service")]
    public class Service
    {

        static ApplicationDbContext db = new ApplicationDbContext();

        [NotMapped]
        public static class Keys
        {
            public static readonly Guid IMSS = Guid.Parse("CD309442-0226-4848-88F9-B1C3B3EFF757");
        }

        [Key]
        public Guid Id { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Int32 SKU { get; set; }

        public String Name { get; set; }

        public String Description { get; set; }

        public Int32? ReferenceLength { get; set; }

        public String PaymentInstruction { get; set; }

        public String Company { get; set; }

        public String LogoUrl { get; set; }

        public Boolean Active { get; set; }

        public DateTime CreatedAt { get; set; }

        public DateTime? DeletedAt { get; set; }

        public string Location { get; set; }

        public Int32? Order { get; set; }

        public String Command { get; set; }

        public Guid ServiceTypeId { get; set; }

        public virtual ServiceType ServiceType { get; set; }

        public Guid ServiceCategoryId { get; set; }

        public virtual ServiceCategory ServiceCategory { get; set; }

        public Guid? ServiceClassificationId { get; set; }

        public virtual ServiceClassification ServiceClassification { get; set; }

        #region methods

     

        [NotMapped]
        public String StringSKU
        {
            get
            {
                return this.SKU.ToString("D6");
            }
        }

        #endregion methods
    }
}

Enpadi_WebUI/Models/ServiceType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Enpadi_WebUI.Models
{
    [Table("ServiceType")]
    public class ServiceType
    {
        [NotMapped]
        public class Keys {

            public static Guid Recharge = Guid.Parse("CD9FCEEF-5E22-48DF-B837-04E6500E37A6");
            public static Guid Pay = Guid.Parse("50C65557-F724-44EB-BC13-920F09866308");
            public static Guid ExternalPayment = Guid.Parse("8F181577-3585-477F-81D9-DBFB2B554EE2");
        }

        [Key]
        public Guid Id { get; set; }
        public int SKU { get; set; }
        public String Name { get; set; }
        public String Description { get; set; }
    }
}

Enpadi_WebUI/Controllers/EnpadiAdminController.cs
using Enpadi_WebUI.Models;
using Enpadi_WebUI.Properties;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Xml;
using System.Xml.Serialization;
using EnpadiSpecialAttributes;

namespace Enpadi_WebUI.Controllers
{
    [Security(ControllerToRedirect = "enpadiadmin", ActionToRedirect = "login")]
    public class EnpadiAdminController : Controller
    {

        #region constructors and inicializers

        private static bool bModoProduccion = Convert.ToBoolean(ConfigurationManager.AppSettings["ModoProduccion"]);

        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;
        //private ApplicationDbContext db = new ApplicationDbContext();

        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        #region constructors

        #endregion constructors and inicializers

        public EnpadiAdminController()
        {
        }

        public EnpadiAdminController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }
        #endregion constructors

        #region views

        public ActionResult UserSettings()
        {

            return View();
        }

        public ActionResult KioskoReport()
        {

            return View();
        }

        // GET: EnpadiAdmin
        public ActionResult Index()
        {
            String userId = User.Identity.GetUserId();
            if (userId == null)
            {
                return RedirectToAction("LogIn");
            }
            else if (Guid.Parse(userId) != ApplicationUser.Key.AdminUserId)
            {
                AuthenticationManager.SignOut();
                return RedirectToAction("LogIn");
            }

            return View();
        }

        public ActionResult Reports()
        {
            String userId = User.Identity.GetUserId();
            if (userId == null)
            {
                return RedirectToAction("LogIn");
            }
            else if (Guid.Parse(userId) != ApplicationUser.Key.AdminUserId)
            {
                AuthenticationManager.SignOut();
                return RedirectToAction("LogIn");
            }

            return View();
        }

        public ActionResult Partner()
        {
            String userId = User.Identity.GetUserId();
            if (userId == null)
            {
                return RedirectToAction("LogIn");
            }
            else if (Guid.Parse(userId) != ApplicationUser.Key.AdminUserId)
            {
                AuthenticationManager.SignOut();
                return RedirectToAction("LogIn");
            }

            return View();
        }

        // GET: EnpadiAdmin
        [AllowAnonymous]
        public ActionResult LogIn(string errorMessage = "")
        {
            ApplicationDbContext db = new ApplicationDbContext();
            String skin = "clean";
            string strSQL = String.Format("SELECT * FROM Skins WHERE name = '{0}'", skin);
            IEnumerable<skin> skinAplicacion = db.Database.SqlQuery<skin>(strSQL);
            ViewBag.skinApp = skinAplicacion.ToList().FirstOrDefault();
            ViewModelWebUsaLogIn model = new ViewModelWebUsaLogIn
            {
                Email = String.Empty,
                Password = String.Empty
            };

            ViewBag.ErrorMessage = errorMessage;

            return View(model);
        }

        // GET: EnpadiAdmin
        public ActionResult Fees()
        {
            String userId = User.Identity.GetUserId();
            if (userId == null)
            {
                return RedirectToAction("LogIn");
            }
            else if (Guid.Parse(userId) != ApplicationUser.Key.AdminUserId)
            {
                AuthenticationManager.SignOut();
                return RedirectToAction("LogIn");
            }

            return View();
        }

        public ActionResult FeeEditor(String id = "")
        {
            ApplicationDbContext db = new ApplicationDbContext();
            ViewModelFeeEditor model = new ViewModelFeeEditor();

            if (id != String.Empty)
            {
                Guid _id = Guid.Parse(id);
                model.Fee = db.Fee.FirstOrDefault(x => x.Id == _id);

                model.PartnerId = (Guid)(model.Fee.PartnerToPayId != null ? model.Fee.PartnerToPayId : Guid.Empty);
                model.PlatformsId = (Guid)(model.Fee.PlatformId != null ? model.Fee.PlatformId : Guid.Empty);
                model.UsersId = (Guid)(model.Fee.UserToPayId != null ? model.Fee.UserToPayId : Guid.Empty);
                model.CurrenciesId = (Guid)(model.Fee.CurrencyId != null ? model.Fee.CurrencyId : Guid.Empty);
                model.ServiceCategoriesId = (Guid)(model.Fee.ServiceCategoryId != null ? model.Fee.ServiceCategoryId : Guid.Empty);

                var noPartner = new SelectListItem { Text = "No Partner", Value = Guid.Empty.ToString() };
                var noPlatform = new SelectListItem { Text = "No Partner", Value = Guid.Empty.ToString() };
                var noUsers = new SelectListItem { Text = "No Partner", Value = Guid.Empty.ToString() };
                var noCurrency = new SelectListItem { Text = "No Partner", Value = Guid.Empty.ToString() };
                var noServiceCategory = new SelectListItem { Text = "No Partner", Value = Guid.Empty.ToString() };

                model.Partner.Add(noPartner);
                model.Partner.AddRange(db.socios
                .Select(x =>
                        new SelectListItem
                        {
                            Value = x.PartnerId.ToString(),
                            Text = x.nombreComercial
                        }).ToList());

                model.Platforms.Add(noPlatform);
                model.Platforms.AddRange(db.Platform
                    .Select(x =>
                        new SelectListItem
                        {
                            Value = x.Id.ToString(),
                            Text = x.Name
                        }).ToList());

                model.Users.Add(noUsers);
                model.Users.AddRange(db.Users
                    .Select(x =>
                        new SelectListItem
                        {
                            Value = x.Id.ToString(),
                            Text = x.Email
                        }).ToList());

                model.Currencies.Add(noCurrency);
                model.Currencies.AddRange(db.monedas
                    .Select(x =>
                        new SelectListItem
                        {
                            Value = x.CurrencyId.ToString(),
                            Text = x.codigo
                        }).ToList());

                model.ServiceCategories.Add(noServiceCategory);
                model.ServiceCategories.AddRange(db.ServiceCategory
                    .Select(x =>
                        new SelectListItem
                        {
                            Value = x.Id.ToString(),
                            Text = x.Name
                        }).ToList());
            }

            return View(model);
        }

        public ActionResult Services()
        {
            return View();
        }

        public ActionResult ServiceEditor(string id)
        {
            ApplicationDbContext db = new ApplicationDbContext();
            servicios model = new servicios();

            if (id != String.Empty)
            {
                Guid _id = Guid.Parse(id);
                model = db.servicios.FirstOrDefault(x => x.Id == _id);

                model.ServiceTypeId = (Guid)(model.ServiceTypeId != null ? model.ServiceTypeId : Guid.Empty);
                model.ServiceCategoryId = (Guid)(model.ServiceCategoryId != null ? model.ServiceCategoryId : Guid.Empty);

                var noServiceType = new SelectListItem { Text = "No Service Type", Value = Guid.Empty.ToString() };
                var noServiceCategory = new SelectListItem { Text = "No Service Category", Value = Guid.Empty.ToString() };

                model.ServiceType.Add(noServiceType);
                model.ServiceType.AddRange(db.ServiceType
                .Select(x =>
                        new SelectListItem
                        {
                            Value = x.Id.ToString(),
                            Text = x.Name
                        }).ToList());

                model.ServiceCategory.Add(noServiceCategory);
                model.ServiceCategory.AddRange(db.ServiceCategory
                    .Select(x =>
                        new SelectListItem
                        {
                            Value = x.Id.ToString(),
                            Text = x.Name
                        }).ToList());

Enpadi_WebUI/Views/EnpadiAdmin/FeeEditor.cshtml
@model Enpadi_WebUI.Models.ViewModelFeeEditor

@{
    ViewBag.Title = "FeeEditor";
    Layout = "~/Views/Shared/_LayoutEnpadiAdmin.cshtml";
}

@section Styles {
    <!-- Section for main scripts render -->

    @Styles.Render("~/Content/website_userindex")
    @Styles.Render("~/Content/datatables")
}
@section Scripts {
    <!-- Section for main scripts render -->
    <!-- Section for main scripts render -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquery/js")
    @Scripts.Render("~/bundles/datatable")
    @Scripts.Render("~/bundles/datatableButtons")
    @Scripts.Render("~/bundles/jquery/currency")
    @Scripts.Render("~/bundles/datatableButtons")
    @Scripts.Render("~/bundles/chartjs/js")
}

<div class="row">
    <div class="col-lg-12">
        <div class="alert alert-success" role="alert" id="successDiv" style="display:none">

        </div>
    </div>
</div>
@using (Html.BeginForm("SaveFee", "EnpadiAdmin", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Fee</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Fee.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Fee.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fee.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fee.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fee.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fee.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fee.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fee.VariableFee, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fee.VariableFee, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fee.VariableFee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fee.FixFee, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fee.FixFee, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fee.FixFee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fee.TaxFee, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fee.TaxFee, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fee.TaxFee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fee.UpperRestriction, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fee.UpperRestriction, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fee.UpperRestriction, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fee.LowerRestriction, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fee.LowerRestriction, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fee.LowerRestriction, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Partner, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.PartnerId, Model.Partner, new { @class = "form-control", @disabled = "disabled", @readonly = "readonly" })

            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.Fee.AllowDelete, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Fee.AllowDelete)
                        @Html.ValidationMessageFor(model => model.Fee.AllowDelete, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>*@

        @*<div class="form-group">
                @Html.LabelFor(model => model.Fee.CreatedByUserId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Fee.CreatedByUserId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Fee.CreatedByUserId, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Currencies, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CurrenciesId, Model.Currencies, new { @class = "form-control", @disabled = "disabled", @readonly = "readonly" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Users, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.UsersId, Model.Users, new { @class = "form-control", @disabled = "disabled", @readonly = "readonly" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServiceCategories, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ServiceCategoriesId, Model.ServiceCategories, new { @class = "form-control", @disabled = "disabled", @readonly = "readonly" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Platforms, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.PlatformsId, Model.Platforms, new { @class = "form-control", @disabled = "disabled", @readonly = "readonly" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @*<input type="submit" value="Save" class="btn btn-default" />*@
                <button type="button" value="Save" onclick="SaveFee();">Save</button>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "fees")
</div>


<script type="text/javascript">

    function SaveFee() {
        var Id = $("#Fee_Id").val();
        var Name = $("#Fee_Name").val();
        var Description = $("#Fee_Description").val();
        var VariableFee = $("#Fee_VariableFee").val();
        var FixFee = $("#Fee_FixFee").val();
        var TaxFee = $("#Fee_TaxFee").val();

        var UpperRestriction = $("#Fee_UpperRestriction").val();
        var LowerRestriction = $("#Fee_LowerRestriction").val();
        var PartnerToPayId = $("#PartnerId").val();
        var AllowDelete = $("#Fee_AllowDelete").val();
        var CurrencyId = $("#CurrenciesId").val();

        var UserToPayId = $("#UsersId").val();
        var ServiceCategoryId = $("#ServiceCategoriesId").val();
        var PlatformId = $("#PlatformsId").val();


        $.ajax({
            url: '@Url.Action("SaveFee", "EnpadiAdmin")',
            contentType: "application/json; charset=utf-8",
            data: {
                id:Id,
                name: Name,
                description: Description,
                variableFee: VariableFee,
                fixFee: FixFee,
                taxFee: TaxFee,

                upperRestriction: UpperRestriction,
                lowerRestriction: LowerRestriction,
                partnerToPayId: PartnerToPayId,
                currencyId: CurrencyId,

                userToPayId: UserToPayId,
                serviceCategoryId: ServiceCategoryId,
                platformId: PlatformId
            },
            dataType: "json",
            success: function (result) {
                    $("#successDiv").show();
                    $("#successDiv").html("<strong>Change on registry!</strong> " + result.Name);
                    console.log("Success");
                },
                error: function (result) {
                    console.log(result);
                }
       });

    }

    $(document).ready(function () {
    });
</script>

Enpadi_WebUI/Views/EnpadiAdmin/LogIn.cshtml
@model Enpadi_WebUI.Models.ViewModelWebUsaLogIn

@{
    ViewBag.Title = "LogIn";
    Layout = "~/Views/Shared/_Layout_Blank.cshtml";
}

@section Styles {
    <!-- Section for main scripts render -->
}

<div class="login-container">
    <div class="row">
        <div class="col-lg-12">
            <img src="~/Images/enpadi-logo.png" width="100%" />
            <div class="text-center m-b-md">
                <h3>Bienvenido al Administrador de Enpadi</h3>
            </div>
            <div class="hpanel">
                <div class="panel-body">
                    <section id="loginForm">
                        @using (Html.BeginForm("LogInValidation", "EnpadiAdmin", FormMethod.Post, new { @class = "form", role = "form" }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            if (ViewBag.ErrorMessage != String.Empty)
                            {
                                <div class="form-group">

                                    <div class="form-group full">
                                        <div class="alert alert-danger">
                                            <strong>Error</strong> @string.Format("{0}", ViewBag.ErrorMessage).
                                        </div>
                                    </div>
                                </div>

                            }

                            <div class="form-group">
                                @Html.LabelFor(m => m.Email, new { @class = "control-label" })
                                @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(m => m.Password, new { @class = "control-label" })
                                @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                            </div>

                            <input type="submit" value="Iniciar Sesión" class="btn btn-primary btn-block" style="background-color:#@ViewBag.skinApp.colorNavBtn" />
                        }
                        <small>
                            <br />
                            Proporcione sus datos de acceso.
                            Si aún no cuenta con una cuenta,
                            favor de comunicarse a Enpadi.
                        </small>

                    </section>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <!-- Section for main scripts render -->
}

Enpadi_WebUI/Views/EnpadiAdmin/Partner.cshtml
@{
    ViewBag.Title = "Partner";
    Layout = "~/Views/Shared/_LayoutEnpadiAdmin.cshtml";
}


@section Styles {
    <!-- Section for main scripts render -->

    @Styles.Render("~/Content/website_userindex")
    @Styles.Render("~/Content/datatables")
}
@section Scripts {
    <!-- Section for main scripts render -->
    <!-- Section for main scripts render -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquery/js")
    @Scripts.Render("~/bundles/datatable")
    @Scripts.Render("~/bundles/datatableButtons")
    @Scripts.Render("~/bundles/jquery/currency")
    @Scripts.Render("~/bundles/datatableButtons")
    @Scripts.Render("~/bundles/chartjs/js")
}

Enpadi_WebUI/Views/EnpadiAdmin/UserSettings.cshtml
@{
    ViewBag.Title = "UserSettings";
    Layout = "~/Views/Shared/_LayoutEnpadiAdmin.cshtml";
}

@section Styles {
    <!-- Section for main scripts render -->

    @Styles.Render("~/Content/website_userindex")
    @Styles.Render("~/Content/datatables")
}
@section Scripts {
    <!-- Section for main scripts render -->
    <!-- Section for main scripts render -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquery/js")
    @Scripts.Render("~/bundles/datatable")
    @Scripts.Render("~/bundles/datatableButtons")
    @Scripts.Render("~/bundles/jquery/currency")
    @Scripts.Render("~/bundles/datatableButtons")
    @Scripts.Render("~/bundles/chartjs/js")
    @Scripts.Render("~/bundles/jqueryval")
}

<div class="row">
    <div class="col-lg-12">
        <h1>Cambio de contraseña</h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <small>
            Seleccione a un usuario para cambiar la contraseña e ingrese la nueva contraseña, no se requiere la
            contraseña pasada para realizar el cambio, este es un proceso administrativo de cambio de contraseña.
        </small>
    </div>
</div>
<hr />



<form id="passwordForm">
    <div class="row form-group">
        <div class="col-lg-4">Seleccione a un usuario</div>
        <div class="col-lg-8">

            <select id="user_email" class="selectpicker form-control" data-live-search="true" onchange="verifyPassword();"></select>
        </div>
    </div>
    <div class="row form-group">
        <div class="col-lg-4">Nueva contraseña</div>
        <div class="col-lg-8">
            <input type="password" class="form-control" id="password" name="password" onkeyup="verifyPassword();" />
        </div>
    </div>
    <div class="row form-group">
        <div class="col-lg-4">Confirmar contraseña</div>
        <div class="col-lg-8">
            <input type="password" class="form-control" id="password_confirm" name="password_confirm" onkeyup="verifyPassword();" />
        </div>
    </div>
    <a id="btnSubmit" class="btn btn-primary" onclick="changeUserPassword();" style="display:none">Cambiar contraseña</a>
</form>



<script type="text/javascript">

    $(document).ready(function () {
        loadUsers();
        configureJqueryValidation();
    });

    function verifyPassword() {

        var password = $("#password").val();
        var password_confirm = $("#password_confirm").val();
        var email = $("#user_email").val();

        if(email != ""){
            if (password.length >= 8) {

                if (password === password_confirm) {
                    $('#btnSubmit').show();
                } else {
                    $('#btnSubmit').hide();
                }
            } else {
                $('#btnSubmit').hide();
            }
        } else {
            $('#btnSubmit').hide();
        }

    }

    function configureJqueryValidation() {

        objMessages = {
            password: {
                required: "Requerido",
                minlength: jQuery.format("La contraseña debe de ser de por lo menos {0} caracteres."),
                equalTo: "Contraseñas no coinciden."
            },
            password_confirm: {
                required: "Requerido",
                minlength: jQuery.format("La contraseña debe de ser de por lo menos {0} caracteres."),
                equalTo: "Contraseñas no coinciden."
            }
        };

        jQuery('#passwordForm').validate({
            lang: "mx",
            rules: {
                password: {
                    minlength: 8
                },
                password_confirm: {
                    minlength: 8,
                    equalTo: "#password"
                }
            },
            messages: objMessages
        });
    }

    function loadUsers() {
        var options = $("#user_email");

        $.ajax({
            url: '@Url.Action("GetAllUsers", "EnpadiAdmin")',
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (result) {

                options.append($("<option />").val("").text("Seleccione a un usuario"));

                $.each(result, function () {
                    options.append($("<option data-tokens=" + this.Email + " />").val(this.Email).text(this.Email));
                });

            },
            error: function (result) {
                console.log(result);
            }
        });
    }

    function changeUserPassword() {

        console.log("change user password method");

        var email = $("#user_email").val();
        var password = $("#password").val();

        $.ajax({
            url: '@Url.Action("Changepassword", "EnpadiAdmin")',
            contentType: "application/json; charset=utf-8",
            data: {
                email: email,
                password: password
            },
            dataType: "json",
            success: function (result) {

              

            },
            error: function (result) {
                console.log(result);
            }
        });

    }
</script>